from typing import TypedDict, Literal

Settings = TypedDict(
    "Settings",
    {
        "app_token": str | None,
        "app_secret": str | None,
        "lang_from": Literal[
            "Auto",
            "English",
            "Chinese (Simplified)",
            "Chinese (Traditional)",
            "Japanese",
            "Korean",
            "French",
            "German",
            "Spanish",
            "Russian",
            "Portuguese",
            "Italian",
            "Vietnamese",
            "Thai",
            "Indonesian",
            "Arabic",
        ],
        "lang_to": Literal[
            "English",
            "Chinese (Simplified)",
            "Chinese (Traditional)",
            "Japanese",
            "Korean",
            "French",
            "German",
            "Spanish",
            "Russian",
            "Portuguese",
            "Italian",
            "Vietnamese",
            "Thai",
            "Indonesian",
            "Arabic",
        ],
    },
)
